### ISSUE TITLE
Allow superstatic over https

### ISSUE THREAD

**Issue by greghuc** [firebase/superstatic#105]
There doesn't seem to be an option to serve superstatic assets over https.
Could this be added?

My use case is that I plan to use divshot.com for static web hosting, where files will be served over https.

I want my local development environment to echo production.
So I'd like my local superstatic server to serve assets over https.

**Comment by tsmgodoi** [comment]
@greghuc 
Do you know if the above solution is still working? I didn't found about it on the docs and I couldn't make it work. Thanks.

**Comment by mbleigh** [comment]
@tsmgodoi you could use superstatic as a middleware [in an HTTPS express app](http://www.hacksparrow.com/express-js-https-server-client-example.html) without much difficulty, I bet.

**Comment by tsmgodoi** [comment]
Thanks @mbleigh,

I've managed to make it work with the plain https-server:
```javascript
'use strict';

var superstatic = require('superstatic');
var connect = require('connect');
var https = require('https');
var fs = require('fs');

var keyFile = process.argv[2];
var certFile = process.argv[3];

var spec = {
  config: {
    public: './app',
    rewrites: [{
      source: '**',
      destination: '/index.html'
    }]
  },
  cwd: process.cwd()
};

var httpsOptions = {
  key: fs.readFileSync(keyFile),
  cert: fs.readFileSync(certFile)
};

var app = connect().use(superstatic(spec));

https.createServer(httpsOptions, app).listen(3474, function(err) {
  if (err) { console.log(err); }
  console.log('Superstatic now serving on port 3474 ...');
});
```

**Comment by specious** [comment]
A solution is to start superstatic and then use the [ngrok](https://ngrok.com/) service as a proxy to the local server which gives you an option to connect securely from the client's point of view:

```
ngrok http 3474
```
