### ISSUE TITLE
Allow for "piggybacking" on another port

### ISSUE THREAD

**Issue by mbleigh** [firebase/superstatic#116]
Several tools such as [broccolijs/broccolicli](/broccolijs/broccoli) and [middleman/middleman](/middleman/middleman) have some kind of static server built into their build chain, but no inherent "watch and build to this directory." Of course I think `--watch` functionality is a great feature, but if the mountain won't come to us...

I propose a `--piggyback [PORT]` option that allows superstatic to "piggyback" onto another running process and proxy to it as a file store. So to use broccoli and superstatic together, I could just do something like:

```
broccoli serve --port 3001 & superstatic --piggyback 3001 --port 3000
```

I would then go to e.g. `http://localhost:3000/about`. Because Superstatic knows to use clean URLs, it makes a proxied request to `http://localhost:3001/about.html`. If it 200s there, superstatic serves up the content. If not, it 404s like you'd expect.

This will allow Superstatic to literally be a layer on top of any other library that can possibly exist, and I think it improves our compatibility story tremendously.

**Comment by abdulhannanali** [comment]
@mbleigh Can I take this up?
