### ISSUE TITLE
Document custom file providers

### ISSUE THREAD

**Issue by scottcorgan** [firebase/superstatic#129]

**Comment by scottcorgan** [comment]
Ideas for useful providers:

* `superstatic-local-provider` - default superstatic provider. Serves local static files.
* `superstatic-s3-provider` - serves files from S3.
* `superstatic -proxy-provider` - serves files proxied from a remote origin.
* `superstatic-dropbox-provider` - serves files from Dropbox.
* `superstatic-github-provider` - serves files from a Github repo.

Upon each you can set the root directory in an options object (among more options based on the type of provider).

Each provider will be required to allow a resolver function to override the provider's default resolving function.

**Comment by scottcorgan** [comment]
Usage:

```js
var connect = require('connect');
var superstatic = require('superstatic');

var app = connect();

app.use(superstatic({
  provider: require('superstatic-local-provider')
});

app.listen():
```

**Comment by abdulhannanali** [comment]
@scottcorgan Would love to work on creating a Github Repo provider initially. If there isn't one already and maintainers are still interested in more provider contributions.

**Comment by scottcorgan** [comment]
@abdulhannanali I'm probably the wrong person to ask since I no longer am involved on the project. I'm going to close the issue since it's mostly irrelevant. This made more sense when Divshot still exists. 👍

**Comment by abdulhannanali** [comment]
awww @scottcorgan! no problem! Thanks for your contributions. There's still documentation for providers in README. So maybe it's relevant.
