### ISSUE TITLE
Livereload vs. BrowserSync

### ISSUE THREAD

**Issue by mbleigh** [firebase/superstatic#145]
Live reloading is good, let's make sure we're using the best tool for the job.

**Comment by scottcorgan** [comment]
BrowserSync looks very useful in regards to keeping things in sync across multiple devices, but looks like something we should consider in Superstatic `3.0`.

**Comment by chinedufn** [comment]
For anyone that wants Superstatic + BrowserSync right now it's easy.

##### Example using Gulp

```
var browserSync = require('browserSync');
var superstatic = require('superstatic');

gulp.task('serve', function() {
  browserSync({
    port: 8000,
    server: {
      baseDir: 'dist',
      middleware: superstatic() // Will automatically read your superstatic.json config file
    }
  });
});
```

**Comment by mbleigh** [comment]
This is not going to be implemented as a middleware-driven integration is preferred to making Superstatic dependent on additional libraries.

**Comment by tomekwi** [comment]
@mbleigh What’s the current way to get live reloading to work now?

**Comment by mbleigh** [comment]
Taken from [recent blog post](https://www.firebase.com/blog/2015-12-16-hosting-improvements.html):

```js
var gulp = require('gulp');
var superstatic = require('superstatic');
var browserSync = require('browser-sync').create();

gulp.task('serve', function() {
  browserSync.init({
    server: {
      middleware: [superstatic({stack: 'strict'})]
    }
  });
  gulp.watch('public/*.html').on('change', browserSync.reload);
});
```

**Comment by tomekwi** [comment]
:+1: Thanks for the heads up!

**Comment by eskalera** [comment]
@mbleigh All I get with that gulp configuration is a screen saying `Cannot GET /` and a `404 Error` in console. Do I need to add something else to my firebase.json file? I never added a superstatic.json file.

**Comment by Andersos** [comment]
@eskalera I'm not getting it to work either. Looks like browser-sync is not using superstatic when configured like https://github.com/firebase/superstatic/issues/145#issuecomment-168774130.

**Comment by AjitsinghKamal** [comment]
@mbleigh There's no need to add a superstatic.json file if you already have a firebase.json .According to the superstatic [documentation](https://github.com/firebase/superstatic#configuration) it will work if any one of them is present .

@eskalera I got mine to work by adding a **baseDir** option pointing to my public directory or whatever directory you want to serve your files from.

```
var gulp = require('gulp');
var superstatic = require('superstatic');
var browserSync = require('browser-sync').create();

gulp.task('serve', function() {
  browserSync.init({
    baseDir: 'public',
    server: {
      middleware: [superstatic({stack: 'strict'})]
    }
  });
  gulp.watch('public/*.html').on('change', browserSync.reload);
});
```

**Comment by roykolak** [comment]
regarding @AjitsinghKamal code sample, `baseDir` should be inside of the `server` config object, like so... 
```js
var gulp = require('gulp');
var superstatic = require('superstatic');
var browserSync = require('browser-sync').create();

gulp.task('serve', function() {
  browserSync.init({
    server: {
      baseDir: 'public',
      middleware: [superstatic({stack: 'strict'})]
    }
  });
  gulp.watch('public/*.html').on('change', browserSync.reload);
});
```
