### ISSUE TITLE
Proposal: Prefix Config Option

### ISSUE THREAD

**Issue by mbleigh** [firebase/superstatic#153]
I propose that we offer the ability to prefix how Superstatic serves an app. For example:

``` json
{
  "prefix":"blog"
}
```

If a prefix is added (it can be any valid pathname), the root directory is served only from that prefix, so "about.html" gets served at "blog/about.html"

All other configuration options including proxies etc. should apply, _however_ they should also work as if the prefix is the root of the app. So a proxy of "/api" would be available at "/blog/api"

This will be useful for third-party developers using Superstatic as a middleware as it will let them easily mount to a prefix.

As to why it's useful for Divshot's future plans, I'll leave it to speculation. :smile:

**Comment by rwjblue** [comment]
:+1: - This would mesh very well with Ember CLI's concept of `baseURL` that is roughly exactly what you are describing.
