### ISSUE TITLE
Proposal: File Manifest

### ISSUE THREAD

**Issue by mbleigh** [firebase/superstatic#157]
I propose a `manifest` option that can be used to selectively expose lists of file paths at the `/__/manifest.json` path.

**Use Case:** I want to make my app available offline. Using the manifest, I fetch a list of all of the files that need to be cached in a Service Worker and aggressively cache them.

Manifest would be specified either as an array or an object. Two examples below:

```js
// the configuration
{
  "manifest": ["**"]
}

// /__/manifest.json endpoint
["index.html","images/logo.png",...]
```

```js
// the configuration
{
  "manifest": {
    "assets":["assets/**"],
    "core":["index.html","dist/*.js"]
  }
}

// /__/manifest.json endpoint
{
  "assets":["assets/abc.jpg","assets/def.jpg"],
  "core":["index.html","dist/app.js","dist/app.min.js"]
}
```

**Comment by developit** [comment]
This seems like a good case for a separate connect/express middleware.

**Comment by mbleigh** [comment]
This probably isn't a candidate for core Superstatic as it's going to demand a much more complex provider story than we're providing in 4.0.
