### ISSUE TITLE
Wildcards for headers

### ISSUE THREAD

**Issue by soluml** [firebase/superstatic#168]
Hey guys,

Was wondering, is there any way for me to wildcard folders/files in the JSON config file?  For example, I'm really wanting to do something like this:

    {
        "root": "public",
        "routes": {
            "**": "index.html"
        },
        "headers": {
            "**/*.{xml,txt,ico,svg,html,js,css}": {
                "content-encoding": "gzip"
            }
        }
    }

Essentially, serve any file with the extensions listed with that header.  Is this a possibility currently?

Thanks!

**Comment by scottcorgan** [comment]
Yep, should work exactly how you have it. Uses [globs]https://github.com/isaacs/node-glob#glob-primer() to match the headers.

**Comment by soluml** [comment]
I have the latest superstatic and it's not working for me.  The above rule doesn't set that header for **any** asset.

If I use `"**": { "content-encoding": "gzip" }` it does work (but encodes my images).

**Comment by scottcorgan** [comment]
Gzipping is on by default, so this wouldn't affect anything. Internally, we use the module [set-headers](https://github.com/divshot/set-headers).

If you want to open  PR with failing tests on that module, I think that would be helpful to solve this problem.

**Comment by mbleigh** [comment]
Superstatic has a middleware-level option to turn gzipping on or off. This is not intended to be controllable at the user-config level. Closing barring an example of this being a general problem.
