### ISSUE TITLE
Filenames with non-english letters fail to load

### ISSUE THREAD

**Issue by dhpollack** [firebase/superstatic#171]
When files with names containing non-english characters (accented latin characters and all non-latin alphabets) are requested from a superstatic server, a "404 not found" error occurs even if the file exists on the server.  This occurs both when uploaded to divshot.io and when testing locally with the "divshot server" command.  Furthermore, other local test servers do not seem to exhibit this behavior, specifically, I have tried Browsersync with Gulp.  Below is the log when attempting to load "ä.m4a" and "a.m4a".  

> 10.240.0.34 - - [13/Jun/2015:15:21:56 +0000] "GET /assets/audio/de/%C3%A4.m4a HTTP/1.1" 404 1174 "-" "-"
> 10.240.236.110 - - [13/Jun/2015:15:22:02 +0000] "GET /assets/audio/de/a.m4a HTTP/1.1" 200 5901 "-" "-"
> 10.240.236.110 - - [13/Jun/2015:15:22:02 +0000] "GET /assets/audio/de/a.m4a HTTP/1.1" 200 5901 "-" "-" 

Note that both "ä.m4a" and "%C3%A4.m4a" work on other servers.

This bug seems to affect all non-latin utf8 characters.  I have seen the issue with German, Hebrew, and Arabic characters.  I have tried setting the encoding in the HTML file to UTF8 with the following tag without any success:

```javascript
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

Let me know if you need any more information.

**Comment by scottcorgan** [comment]
This is a known issue. The way file names are parsed and diffed breaks with non-english or special ascii characters.

I'd be very open to a PR while I investigate.
