### ISSUE TITLE
Ensure '304 not modified' doesn't happen?

### ISSUE THREAD

**Issue by rstacruz** [firebase/superstatic#200]
Is there a way to stop superstatic from returning "304 not modified" statuses?

The reason for this is that for development, I'd like to use a `connect` middleware to modify the response. this can't happen when I get 304's.

**Comment by rstacruz** [comment]
actually, nevermind. I can do this with another connect middleware that conditionally removes `if-none-match` and `if-modified-since` headers :)

**Comment by mbleigh** [comment]
:+1:
