### ISSUE TITLE
superstatic.org seems down

### ISSUE THREAD

**Issue by beeman** [firebase/superstatic#203]
Not an issue with the application itself but I thought this might be a good place to notify you guys that the website superstatic.org is down for me since yesterday. 

It seems to be down from other places too: http://isup.me/superstatic.org

**Comment by beeman** [comment]
Project seems abandonded. A shame really, it has nice potencial with all those SPA's nowadays

**Comment by mbleigh** [comment]
Superstatic is still actively used to power [Firebase Hosting](https://firebase.google.com/docs/hosting/). We've retired superstatic.org since it didn't really have much value beyond the GitHub READM.
