### ISSUE TITLE
Document URL patterns

### ISSUE THREAD

**Issue by joeyespo** [firebase/superstatic#209]
I'm setting some cache headers and trying to figure out how to write the source URL.

I see that you can star `*` and double-star `**` URLs to match paths. I also see [there's more to it](https://github.com/firebase/superstatic#configuration) with `@`:

``` json
{
  "headers": [
    {
      "source" : "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
```

Can these be combined? `@(index.html|some/**/path)`

Can all the possibilities be documented in the README?

Thanks!

**Comment by joeyespo** [comment]
Oh, I see it's a glob pattern and is [documented in Firebase](https://www.firebase.com/docs/hosting/guide/full-config.html#section-glob).

Might be good to copy or reference that. It's very clear.

**Comment by bkendall** [comment]
If there's a case you'd like to see in our `README`, please feel free to submit a PR with the use case. Thanks!
