### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by mbrevda** [firebase/superstatic#210]
Due to some unfortunate circumstances, I'm forced to pass base64'd json via the url. The problem becomes when the path's length is [greater than 1060](http://stackoverflow.com/a/32408084/747749) (or somewhere about there, at least for os x) and it causes stat to fail.

While there isn't anything this project can do about os limitations, I do have an idea. In general, the fs is checked for a matching file before trying to match. Would it be possible to add a setting that says ALWAYS use the rewrite value, without checking the fs for matching files? A side benefit of this would be a tiny improvement in performance for single page apps that may have lots of urls all mapped back to the same index.html.

**Comment by mbleigh** [comment]
I don't think it'd be wise to make that configurable (how would your spa
load js etc if it doesn't check the static file first) but I'd be
interested in a PR that added explicit not found behavior to the fs
provider when an enametoolong error occurs.
