### ISSUE TITLE
Support rewrite path

### ISSUE THREAD

**Issue by kunyan** [firebase/superstatic#225]
Current rewrite only support destination should be a exist file.
How about support rewrite path?

**Comment by mbleigh** [comment]
What would this accomplish? That path would have to be a file or it would
404

**Comment by kunyan** [comment]
@mbleigh  for support some legacy url  , if it has many files,  add everyone of them in the config file seems very bad

**Comment by mbleigh** [comment]
Can you give me an example of what you wish you could do? I don't think I'm
following
