### ISSUE TITLE
SuperStatic site gives DNS Error

### ISSUE THREAD

**Issue by abdulhannanali** [firebase/superstatic#232]
When I opened superstatic.org, I got this DNS Error

![image](https://user-images.githubusercontent.com/8170969/27381288-adb39970-569b-11e7-9caf-5c8066ecf70c.png)

I am opening this site from Pakistan and I am on Chrome v45, however, it seems like an issue with the DNS Configuration.

**Comment by mbleigh** [comment]
We've turned down the superstatic.org site -- the GitHub repo is now the homepage

**Comment by abdulhannanali** [comment]
Seems fair, it has all the info required. Thanks!

**Comment by abdulhannanali** [comment]
@mbleigh Just a question, is superstatic used in production at Firebase? I mean that'd be so damn cool.

**Comment by mbleigh** [comment]
Yup! Firebase Hosting runs Superstatic under the hood. That's why `firebase serve` and Firebase Hosting have the same behavior :smile:

**Comment by abdulhannanali** [comment]
That  means it's quite battle tested, going to use this for hosting all my static sites in future. Much better than other options such as ecstatic. Do you have any issues open  for me to work on? Would love to contribute, however, there doesn't seem anything major. I would appreciate any pointers.

**Comment by abdulhannanali** [comment]
@mbleigh

**Comment by mbleigh** [comment]
Don't have anything in particular to point you at at the moment, but thanks for offering!

**Comment by abdulhannanali** [comment]
@mbleigh I will appreciate if you can find something and open issues. I will keep an eye on them.
