### ISSUE TITLE
Incompatibility with GCC <4.8

### ISSUE THREAD

**Issue by pl12133** [firebase/superstatic#240]
This morning while attempting to upgrade `superstatic` to `v4.2.0` our continuous integration has broken. It appears that we are now encountering MayhemYDG/iltorb#23.

I do not expect any action on your end since this is an upstream requirement, but I thought I would file an issue to track the breakage. If may be useful to include a link to the [`MayhemYDG/iltorb` "Prerequisites for Building" section](https://github.com/MayhemYDG/iltorb#prerequisites-for-building) to inform others of this requirement.

Workarounds include downgrading below `v4.2.0`.

**Comment by mbleigh** [comment]
I'm surprised that your build failed -- we ran into this during our own testing and explicitly made the dependency optional to have a clean fallback. Can you share exactly how it failed (spewing a bunch of warning text is more or less expected).

**Comment by pl12133** [comment]
It looks like this warning was a red herring and that install was handled gracefully, it was actually extraneous dependencies causing the failure:

```sh
npm ERR! extraneous: multipipe@0.3.1 /$BUILD_PATH/node_modules/multipipe
npm ERR! extraneous: stream-buffers@3.0.1 /$BUILD_PATH/node_modules/stream-buffers
```

This is most certainly an issue on my end, so I'll close this out. Sorry for the false alarm!
