### ISSUE TITLE
Feature: Show directory listings

### ISSUE THREAD

**Issue by qiangbro** [firebase/superstatic#250]
hi, I want to get a clean view of all available files in the current directory,
just like http-server's -d option, eg: 'http://127.0.0.1:8080/' shows:
![ihaier 20180130105717](https://user-images.githubusercontent.com/4646469/35545906-6c3f2ea8-05ac-11e8-91dd-57c80d1d799e.jpg)

Would you add a simple config to superstatic.json, so that superstatic can enable this function?
eg: `{ show_directory_listings : true}`

**Comment by 4cm4k1** [comment]
This could be cool. If it’s something the project wants to support, whoever implements this might want to take a look at https://github.com/zeit/serve for inspiration. 😄

**Comment by bkendall** [comment]
I don't see this being a use case we would support in the near future. A PR is always welcome, but we won't be working on it at this time.
