### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by Oduig** [firebase/superstatic#251]
I'm considering using superstatic, but I noticed there's very little activity since ~ October 2017. Hope this is the right way to ask the question - is the project still active? If not, for the readers, what are your alternatives?

**Comment by merlinnot** [comment]
No answer is sometimes the best answer.

**Comment by mbleigh** [comment]
This project is depended on by the Firebase CLI and is actively (but sporadically) maintained by the Firebase team. It is largely considered a stable project that won't need many changes.
