### ISSUE TITLE
Serving site landing page results in "Unexpected error occurred" for v6.0.x

### ISSUE THREAD

**Issue by chalin** [firebase/superstatic#260]
### Version info

```console
> superstatic --version
6.0.1
```

### Platform Information

MacOS

### Steps to reproduce

 1. Clone and setup https://github.com/dart-lang/site-www (see setup instructions in the README).
 2. Launch `superstatic` using this script: `./scripts/serve.sh`.
 3. Visit [localhost:400](http://localhost:4000).

### Expected behavior

The visited page should load.
Note that it loads fine with **superstatic@5.0.2**.

### Actual behavior

You'll see this in the browser: 'Unexpected error occurred.', and this in the terminal where the server was launched:

```nocode
Error: {"redirect":""} is not a recognized responder directive
```

The firebase config file is: https://github.com/dart-lang/site-www/blob/master/firebase.json.

Related:
- This breaks builds on Travis, see https://github.com/dart-lang/site-www/issues/1051
- Firebase-tools also has issues, see https://github.com/firebase/firebase-tools/issues/876

cc @kwalrath @filiph @kevmoo @mbleigh

**Comment by bkendall** [comment]
Fixed with #262
