### ISSUE TITLE
simplify compression configuration

### ISSUE THREAD

**Issue by frankli0324** [firebase/superstatic#404]
allow configuring compression with cli options or configuration file
compression is a feature that is quite commonly used, I believe

**Comment by bkendall** [comment]
What kinds of compression options are you interested in? `compression` is a config that we do include (to gzip content) - I'd have to check/verify that it's in the CLI's flags. But is there something you have in mind?

**Comment by frankli0324** [comment]
I mean exactly the `compression` option. hoping for it to be included in cli flags 🙏

**Comment by bkendall** [comment]
Truth be told, it's probably not something I can get to and implement in a
reasonable timeframe (the CLI flags aren't the usual way we usually use
this module) but a PR would always be welcome!

**Comment by frankli0324** [comment]
Will do this weekend:)
just realized that this issue is numbered 404

**Comment by frankli0324** [comment]
sorry but it turns out that superstatic does support `--compression`, but not mentioned in README.
