### ISSUE TITLE
Update glob > 9.0.0

### ISSUE THREAD

**Issue by joehan** [firebase/superstatic#469]
This package currently uses glob<v9, which transitively depends on inflight, which is deprecated due to leaking memory.

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
To fix this, just update glob to >9.0.0

**Comment by bkendall** [comment]
```
superstatic » npm ls --omit=dev glob
superstatic@9.0.3
└─┬ re2@1.21.2
  └─┬ node-gyp@10.1.0
    ├── glob@10.4.1
    └─┬ make-fetch-happen@13.0.1
      └─┬ cacache@18.0.3
        └── glob@10.4.1
```

`re2` is the dependency on glob in the non-dev dependencies, and that is up to date. I've looked at the other uses and they're scattered in the dev dependencies and aren't easily updated, so I'm going to close this for now.
